const VERT = `attribute vec3 p;attribute vec3 c;uniform mat4 vp;uniform mat4 model;varying vec3 color;varying float depth;void main(){vec4 world=model*vec4(p,1.);gl_Position=vp*world;color=c;depth=gl_Position.w;}`
const FRAG = `precision mediump float;varying vec3 color;varying float depth;uniform vec3 fog;void main(){float f=clamp((depth-28.)/115.,0.,.82);gl_FragColor=vec4(mix(color,fog,f),1.);}`
function mul(a,b){const o=new Float32Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,asp,n,f){const t=1/Math.tan(fov/2),o=new Float32Array(16);o[0]=t/asp;o[5]=t;o[10]=(f+n)/(n-f);o[11]=-1;o[14]=2*f*n/(n-f);return o}
function look(eye,at){let zx=eye[0]-at[0],zy=eye[1]-at[1],zz=eye[2]-at[2],l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=zz,xz=-zx;l=Math.hypot(xx,xz);xx/=l;xz/=l;const yx=zy*xz,yz=-zy*xx;return new Float32Array([xx,yx,zx,0,0,Math.hypot(zx,zz),zy,0,xz,yz,zz,0,-xx*eye[0]-xz*eye[2],-yx*eye[0]-Math.hypot(zx,zz)*eye[1]-yz*eye[2],-zx*eye[0]-zy*eye[1]-zz*eye[2],1])}
function model(x,y,z,sx=1,sy=1,sz=1,ry=0){const c=Math.cos(ry),s=Math.sin(ry);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1])}
const cube=[-1,-1,-1, 1,-1,-1, 1,1,-1,-1,-1,-1,1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,1,1,1,-1,-1,1,1,1,1,-1,1,1,-1,-1,-1,-1,1,-1,-1,1,1,-1,-1,-1,-1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1,-1,-1,1,1,-1,1,1,1,1,-1,1,1,-1,-1,1,1,-1,-1,1,1,-1,1,-1,1,1,1,1]
function cone(n=8){const a=[];for(let i=0;i<n;i++){let q=i/n*Math.PI*2,r=(i+1)/n*Math.PI*2;a.push(0,1,0,Math.cos(q),-1,Math.sin(q),Math.cos(r),-1,Math.sin(r));a.push(0,-1,0,Math.cos(r),-1,Math.sin(r),Math.cos(q),-1,Math.sin(q))}return a}
function mesh(gl,verts,color){const colors=[];for(let i=0;i<verts.length/3;i++){const shade=.82+(i%3)*.07;colors.push(color[0]*shade,color[1]*shade,color[2]*shade)}const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);const cb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(colors),gl.STATIC_DRAW);return{b,cb,n:verts.length/3}}
export function createWorld(canvas,onUpdate){const gl=canvas.getContext('webgl',{antialias:true});if(!gl)return()=>{};const sh=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);return s},pr=gl.createProgram();gl.attachShader(pr,sh(gl.VERTEX_SHADER,VERT));gl.attachShader(pr,sh(gl.FRAGMENT_SHADER,FRAG));gl.linkProgram(pr);gl.useProgram(pr);const loc={p:gl.getAttribLocation(pr,'p'),c:gl.getAttribLocation(pr,'c'),vp:gl.getUniformLocation(pr,'vp'),m:gl.getUniformLocation(pr,'model'),fog:gl.getUniformLocation(pr,'fog')};gl.enableVertexAttribArray(loc.p);gl.enableVertexAttribArray(loc.c);const meshes={rock:mesh(gl,cube,[.29,.35,.34]),wood:mesh(gl,cube,[.29,.15,.09]),wall:mesh(gl,cube,[.55,.39,.24]),roof:mesh(gl,cone(4),[.19,.12,.11]),pine:mesh(gl,cone(9),[.08,.25,.18]),snow:mesh(gl,cone(9),[.72,.84,.85]),skin:mesh(gl,cube,[.74,.45,.28]),coat:mesh(gl,cube,[.18,.42,.58]),gold:mesh(gl,cone(6),[1,.65,.15]),lake:mesh(gl,cube,[.12,.64,.69])};
 meshes.mountain=mesh(gl,cone(10),[.25,.33,.34]);
 const objects=[];const add=(type,x,y,z,sx,sy,sz,ry=0)=>objects.push({type,m:model(x,y,z,sx,sy,sz,ry)});
 // ground stepped terraces
 for(let x=-60;x<=60;x+=6)for(let z=-65;z<=55;z+=6){const y=-2+Math.sin(x*.08)*1.2+Math.cos(z*.06)*.7+Math.max(0,-z-12)*.045;add('rock',x,y,z,3.15,.7,3.15,0)}
 // houses and warm village
 [[-12,0,-5],[0,.2,-10],[13,0,-2],[-20,.3,8],[20,.2,10],[-4,.3,12]].forEach(([x,y,z],i)=>{add('wall',x,y+1.5,z,4,2.5,3,i*.25);add('roof',x,y+5,z,5.4,2.4,4.4,i*.25);add('gold',x+2.5,y+2,z-3.1,.5,.7,.12,i*.25)})
 // forests
 for(let i=0;i<55;i++){const a=i*2.4,x=Math.sin(a)* (32+i%18),z=Math.cos(a*.71)*(30+i%24)-4;if(Math.abs(x)<25&&Math.abs(z)<20)continue;const y=-.5+Math.max(0,-z-12)*.045;add('wood',x,y+2,z,.45,2.5,.45);add('pine',x,y+6,z,2.5,5.8,2.5)}
 // mountains and lake
 [[-55,10,-65,24,35,24],[5,14,-82,32,45,32],[58,12,-70,27,38,27]].forEach(v=>{add('mountain',...v);add('snow',v[0],v[1]+24,v[2],v[3]*.55,v[4]*.42,v[5]*.55)});add('lake',34,1,-36,15,.18,10);add('wall',45,2,-35,3,2,2);add('roof',45,5,-35,4,2,3);
 // prayer poles
 for(let i=0;i<7;i++){add('wood',-10+i*3,5,1,.12,5,.12);add('gold',-9+i*3,8.4,1,.9,.35,.05)}
 const draw=(o)=>{const q=meshes[o.type];gl.bindBuffer(gl.ARRAY_BUFFER,q.b);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,q.cb);gl.vertexAttribPointer(loc.c,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(loc.m,false,o.m);gl.drawArrays(gl.TRIANGLES,0,q.n)}
 const keys=new Set(),player={x:-3,z:23,yaw:0},target={x:-3,z:8};let camYaw=0,camPitch=.28,last=performance.now(),running=true,drag=false,stamina=100;
 const down=e=>{keys.add(e.key.toLowerCase())},up=e=>keys.delete(e.key.toLowerCase()),md=e=>{drag=true;canvas.requestPointerLock?.()},mu=()=>drag=false,mm=e=>{if(document.pointerLockElement===canvas||drag){camYaw-=e.movementX*.0025;camPitch=Math.max(.08,Math.min(.58,camPitch-e.movementY*.0018))}},wheel=e=>{distance=Math.max(7,Math.min(18,distance+e.deltaY*.01))};let distance=10;
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);canvas.addEventListener('mousedown',md);window.addEventListener('mouseup',mu);window.addEventListener('mousemove',mm);canvas.addEventListener('wheel',wheel,{passive:true});
 function frame(now){if(!running)return;const dt=Math.min((now-last)/1000,.04);last=now;let f=0,r=0;if(keys.has('w')||keys.has('arrowup'))f++;if(keys.has('s')||keys.has('arrowdown'))f--;if(keys.has('d')||keys.has('arrowright'))r++;if(keys.has('a')||keys.has('arrowleft'))r--;let sprint=keys.has('shift')&&stamina>0,sp=sprint?10:5.2;if(f||r){const l=Math.hypot(f,r);f/=l;r/=l;player.x+=(Math.sin(camYaw)*f+Math.cos(camYaw)*r)*sp*dt;player.z+=(Math.cos(camYaw)*f-Math.sin(camYaw)*r)*sp*dt;player.yaw=Math.atan2(Math.sin(camYaw)*f+Math.cos(camYaw)*r,Math.cos(camYaw)*f-Math.sin(camYaw)*r);stamina=Math.max(0,stamina-(sprint?24:-12)*dt)}else stamina=Math.min(100,stamina+20*dt);player.x=Math.max(-57,Math.min(57,player.x));player.z=Math.max(-55,Math.min(48,player.z));
  const d=Math.cos(camPitch)*distance,eye=[player.x-Math.sin(camYaw)*d,4+Math.sin(camPitch)*distance,player.z-Math.cos(camYaw)*d],at=[player.x,2.2,player.z];canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.34,.56,.67,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.uniform3f(loc.fog,.48,.66,.72);gl.uniformMatrix4fv(loc.vp,false,mul(perspective(.9,canvas.width/canvas.height,.1,220),look(eye,at)));objects.forEach(draw);
  // player avatar, readable third person silhouette
  draw({type:'coat',m:model(player.x,1.8,player.z,.75,1.25,.5,player.yaw)});draw({type:'skin',m:model(player.x,3.55,player.z,.48,.48,.48,player.yaw)});draw({type:'wood',m:model(player.x-.48,1.9,player.z,.14,1,.14,player.yaw)});draw({type:'wood',m:model(player.x+.48,1.9,player.z,.14,1,.14,player.yaw)});draw({type:'rock',m:model(player.x-.35,.25,player.z,.22,.85,.25,player.yaw)});draw({type:'rock',m:model(player.x+.35,.25,player.z,.22,.85,.25,player.yaw)});
  // objective beacon
  draw({type:'gold',m:model(target.x,3+Math.sin(now*.003)*.3,target.z,.45,1,.45)});onUpdate?.({x:player.x,z:player.z,stamina,near:Math.hypot(player.x-target.x,player.z-target.z)<4});requestAnimationFrame(frame)}requestAnimationFrame(frame);
 return{setTarget(x,z){target.x=x;target.z=z},destroy(){running=false;window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('mousemove',mm);window.removeEventListener('mouseup',mu)}}}
